# Generated by Django 5.0.2 on 2024-04-28 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Foodie_Joint', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='location',
        ),
        migrations.AddField(
            model_name='account',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='picture',
            field=models.ImageField(blank=True, default='images/foodie-joint-logo.png', null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='account',
            name='state',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Foodie_Joint.account'),
        ),
        migrations.AddField(
            model_name='location',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Foodie_Joint.account'),
        ),
        migrations.AlterField(
            model_name='itemreview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Foodie_Joint.account'),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Foodie_Joint.account'),
        ),
        migrations.DeleteModel(
            name='ItemTag',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
