# Generated by Django 5.0.2 on 2024-04-28 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Foodie_Joint', '0002_remove_tag_location_account_bio_account_city_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='picture',
            new_name='profile_picture',
        ),
    ]
