# Generated by Django 5.0.2 on 2024-05-01 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Foodie_Joint', '0003_alter_item_name_alter_location_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='address',
            field=models.CharField(error_messages={'unique': 'This address is already in use'}, max_length=50, unique=True),
        ),
    ]
