# Generated by Django 5.0.2 on 2024-05-01 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Foodie_Joint', '0004_alter_location_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(error_messages={'unique': 'This Item Already Exists'}, max_length=50, unique=True),
        ),
    ]
