# Generated by Django 5.0.2 on 2024-03-09 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Foodie_Joint', '0005_remove_review_type_review_location_itemreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='location',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Foodie_Joint.location'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ItemTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Foodie_Joint.item')),
            ],
        ),
    ]
