# Generated by Django 5.0.2 on 2024-03-12 23:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Foodie_Joint', '0008_alter_review_num_stars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='num_stars',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')]),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Foodie_Joint.user'),
        ),
    ]
