# Generated by Django 5.0.2 on 2024-03-13 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Foodie_Joint', '0009_alter_review_num_stars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='num_stars',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')]),
        ),
    ]
