# Generated by Django 5.0.2 on 2024-03-12 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Foodie_Joint', '0009_alter_review_num_stars_alter_review_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.CharField(max_length=10),
        ),
    ]
