# Generated by Django 5.0.2 on 2024-03-13 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Foodie_Joint', '0011_alter_itemreview_num_stars'),
        ('Foodie_Joint', '0011_alter_review_user'),
    ]

    operations = [
    ]
