# Generated by Django 5.0.2 on 2024-03-30 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Foodie_Joint', '0013_locationtag_alter_review_user_location_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationtag',
            name='name',
            field=models.CharField(choices=[('Salads', 'Salads'), ('Breakfast', 'Breakfast'), ('Gluten Free', 'Gluten Free'), ('Burger', 'Burger'), ('Brunch', 'Brunch'), ('Mexican', 'Mexican'), ('Sandwiches', 'Sandwiches'), ('Pizza', 'Pizza'), ('Dessert', 'Dessert'), ('Chinese', 'Chinese'), ('Lunch', 'Lunch'), ('Coffee', 'Coffee'), ('Vegan', 'Vegan'), ('Outside Dining', 'Outside Dining'), ('Vegetarian', 'Vegetarian'), ('Fast Food', 'Fast Food'), ('Seafood', 'Seafood'), ('Dinner', 'Dinner'), ('Bar', 'Bar'), ('Pet Friendly', 'Pet Friendly'), ('Food', 'Food'), ('Italian', 'Italian'), ('Drink', 'Drink'), ('Fine Dining', 'Fine Dining')], max_length=50),
        ),
    ]
