# Generated by Django 5.0.2 on 2024-03-31 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Foodie_Joint', '0013_alter_review_user'),
        ('Foodie_Joint', '0016_alter_locationtag_name'),
    ]

    operations = [
    ]
