# Generated by Django 5.0.2 on 2024-03-31 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Foodie_Joint', '0018_item_image_location_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, default='images/foodie-joint-logo.png', null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='location',
            name='image',
            field=models.ImageField(blank=True, default='images/foodie-joint-logo.png', null=True, upload_to='images/'),
        ),
    ]
