# Generated by Django 5.0.2 on 2024-03-31 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Foodie_Joint', '0019_alter_item_image_alter_location_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, default='static/images/foodie-joint-logo.png', null=True, upload_to='images/'),
        ),
    ]
