# Generated by Django 5.0.2 on 2024-04-16 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Foodie_Joint', '0023_account_delete_user_alter_location_favorites'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='firstName',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='lastName',
            new_name='last_name',
        ),
        migrations.RemoveField(
            model_name='account',
            name='email',
        ),
        migrations.RemoveField(
            model_name='account',
            name='password',
        ),
        migrations.RemoveField(
            model_name='account',
            name='username',
        ),
    ]
