# Generated by Django 5.0.2 on 2024-04-16 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Foodie_Joint', '0024_rename_firstname_account_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='account',
            name='last_name',
        ),
    ]
