# Generated by Django 5.0.2 on 2024-04-17 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Foodie_Joint', '0027_alter_location_favorites'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='is_recommended',
            field=models.BooleanField(default=False),
        ),
    ]
