"""
Django settings for django_project project.

Generated by 'django-admin startproject' using Django 5.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-4ju2n@$f9d0c=h)_g0lbb%k9&@rf(xa$d$g$&5ri$uf)*gev^4'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    ".replit.dev", ".replit.app", "127.0.0.1:8000",
    '9bce0e11-b6ba-4a1d-9b73-5b768fefccca-00-3emf0wwbd1vei.janeway.repl.co',
    '5a25ef20-82cf-42d6-b716-69fbbe1fa9c3-00-310a111myqeeh.kirk.repl.co',
  '97787d57-f143-4546-958d-6aa4f5b76cfa-00-2zy3yjsid1ls0.kirk.repl.co',
  '658b463e-14cd-4853-bd0e-cb12529f90c2-00-3ne0f11err3re.janeway.repl.co',
  '6349a396-d958-48e7-85c4-8e2eaae44781-00-2fd7v2wdro19k.janeway.repl.co'
]

CSRF_TRUSTED_ORIGINS = ["https://*.replit.dev", "https://*.replit.app", 
"https://9bce0e11-b6ba-4a1d-9b73-5b768fefccca-00-3emf0wwbd1vei.janeway.repl.co", 
"https://5a25ef20-82cf-42d6-b716-69fbbe1fa9c3-00-310a111myqeeh.kirk.repl.co",
"https://658b463e-14cd-4853-bd0e-cb12529f90c2-00-3ne0f11err3re.janeway.replit.dev",                 
'https://97787d57-f143-4546-958d-6aa4f5b76cfa-00-2zy3yjsid1ls0.kirk.repl.co', 
"https://658b463e-14cd-4853-bd0e-cb12529f90c2-00-3ne0f11err3re.janeway.repl.co"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'Foodie_Joint',
    'bootstrap5',
    #'django-crontab'
]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'django_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'django_project.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME':
        'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME':
        'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME':
        'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME':
        'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field
MEDIA_ROOT =  os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

#CRONJOBS = [
 # ('0 0 * * *', 'FoodieJoint.cron.send_daily_email')
#]